### PR TITLE
List esp32 as supported architecture.

### PR DESCRIPTION
**Pull request by generationmake**
tested with an esp32-board. compiled with no errors. examples worked.

### CODE REVIEW

**Comment by per1234** [comment]
I'm happy to add compilation of the examples for an ESP32 board to the CI system in order to help ensure the continuation of the promised support for this architecture if you like.

**Comment by aentinger** [comment]
@per1234 that would be fantastic!

**Comment by per1234** [comment]
Would you like me to submit a PR against this "add-esp32" branch to add it to this PR, or do it as a separate PR against the master branch?

**Comment by aentinger** [comment]
I'd prefer if you'd directly commit to this branch since merging this branch implies ESP32 support and I'd prefer CI support and smoke test before that.

**Comment by per1234** [comment]
OK, it is done. I think we'll meet [our old friend `-Werror`](https://github.com/espressif/arduino-esp32/blob/1.0.4/platform.txt#L21) once again.

**Comment by aentinger** [comment]
I was afraid of something like that which is why I wanted a CI run first. I'm going to fix that one tomorrow.

**Pull request merged**
