### PR TITLE
added 12mhz and CANopen support

### PR DESCRIPTION
**Pull request by munzili**
This pull requests adds

- CANopen support by setting sample point to 87.5% as close as possible
- Adding new baudrates 10, 20, 50, 100 and 800kbps where possible
- Adding 12mhz chips

### CODE REVIEW

**Comment by munzili** [comment]
Baudrates calculation was done with:
https://www.kvaser.com/support/calculators/bit-timing-calculator/

**Comment by munzili** [comment]
Well, actually i need 12mhz support AND different baudrates. 

if you wish, i change the PR to only support the new baudrates and the 12mhz chip and leave the old values. I tested 12mhz  with 20kbps.

The new values should be conform with the CANopen standard based on this document https://www.can-cia.org/fileadmin/resources/documents/proceedings/2003_koppe.pdf by setting the baudrates and the sample point to the values defined in the document

**Comment by munzili** [comment]
Well, actually i need 12mhz support AND different baudrates. 

if you wish, i change the PR to only support the new baudrates and the 12mhz chip and leave the old values. I tested 12mhz  with 20kbps.

The new values should be conform with the CANopen standard based on this document https://www.can-cia.org/fileadmin/resources/documents/proceedings/2003_koppe.pdf by setting the baudrates and the sample point to the values defined in the document

**Comment by aentinger** [comment]
>if you wish, i change the PR to only support the new baudrates and the 12mhz chip and leave the old values. I tested 12mhz with 20kbps.

That would be an acceptable proposition.

**Comment by aentinger** [comment]
Btw. controller type in your online calculator seems to only support MCP25**10**. Not sure on the difference though. Here seems to be another tool: https://intrepidcs.com/products/free-tools/mb-time-calculator/ . Anything you can do to increase my confidence in this change would be appreciated.

**Comment by munzili** [comment]
https://ww1.microchip.com/downloads/en/Appnotes/00872a.pdf

the MCP2515 is based on MCP2510 but CNF flags are equal

**Comment by aentinger** [comment]
>The MCP2515 is based on MCP2510 but CNF flags are equal except CNF3 7bit but this bit was not setted before too

Works for me :+1: . Only the changes for 12 MHz then plus your missing baud rates.

**Comment by aentinger** [comment]
So you'd be doing some testing with this value @generationmake ?

**Comment by munzili** [comment]
I have restored the original flag definitions

**Review by aentinger — APPROVED** [review]
LGTM :+1: Thank you @munzili :coffee: :wave:

**Pull request merged**
