### PR TITLE
Adding support for MCP2515 with different crystals 

### PR DESCRIPTION
**Pull request by echoGee**
Atleast some of the boards have different crystals. Supporting this with the PR

### CODE REVIEW

**Comment by echoGee** [comment]
@aentinger Could you check this PR ? trying to find the failed checks. Could you help?

**Comment by per1234** [comment]
@echoGee you can see them here:
- https://github.com/107-systems/107-Arduino-MCP2515/runs/1786024546?check_suite_focus=true
- https://github.com/107-systems/107-Arduino-MCP2515/runs/1786024547?check_suite_focus=true#step:4:19

I think if you take a close look at the error messages, the problems will become clear. After fixing them, you can push commits to the `master` branch of your fork of this repository and the checks will automatically run again.

**Review by echoGee — COMMENTED** [review]
Fixing CI issues

**Comment by echoGee** [comment]
fixing the CI issues with extra spaces and regression with a function parameter name.

**Comment by echoGee** [comment]
Is there any other action item before this PR merges with master ?

**Review by aentinger — APPROVED** [review]
LGTM :+1: Thank you for the contribution 🚀

**Pull request merged**
